const ActionTypes = {
  ///Search Gists
  SEARCH_GISTS_REQUEST: "SEARCH_GISTS_REQUEST",
  SEARCH_GISTS_SUCCESS: "SEARCH_GISTS_SUCCESS",
  SEARCH_GISTS_FAIL: "SEARCH_GISTS_FAIL",

  //Gist Detail
  GISTS_DETAIL_REQUEST: "GISTS_DETAIL_REQUEST",
  GISTS_DETAIL_SUCCESS: "GISTS_DETAIL_SUCCESS",
  GISTS_DETAIL_FAIL: "GISTS_DETAIL_FAIL",
};

export default ActionTypes;
